"""Initial migration

Revision ID: e3e0c930cdf1
Revises: 
Create Date: 2025-05-30 15:57:39.860109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3e0c930cdf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_blocklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', postgresql.CIDR(), nullable=False),
    sa.Column('num_blocks', sa.Integer(), nullable=False),
    sa.Column('time_added', sa.DateTime(), nullable=False),
    sa.Column('time_unblocked', sa.DateTime(), nullable=False),
    sa.Column('duration', postgresql.INTERVAL(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('netid', sa.String(length=128), nullable=False),
    sa.Column('api_token', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_blocklist')
    # ### end Alembic commands ###
